# Generated by Django 4.2 on 2023-04-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_livro_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro'},
        ),
    ]
